FROM node:latest as builder
WORKDIR /app
COPY . /app
RUN npm install \
 && npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/dist /var/www/myapp/dist
COPY default.conf /etc/nginx/conf.d/default.conf 